version: '3.4'

networks:
  remo-net:
    driver: bridge

services:
  mongo-server:
    image: "mongo:latest"
    networks:
      - remo-net
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
      - ./data:/data/db
  remosys.api:
    image: ${DOCKER_REGISTRY-}remosysapi
    build:
      context: .
      dockerfile: Remosys.Api/Dockerfile
    networks:
      - remo-net
    ports:
      - "8000:80"
      - "44348:443"
    links: 
      - mongo-server
    depends_on:
      - 'mongo-server'
  redis-server:
    image: "redis"
    volumes:
        - /etc/redis/:/data 
    networks:
      - remo-net  
    ports:
      - '6379:6379'
    restart: unless-stopped
  seq3-server:
    image: 'datalust/seq:latest'
    networks:
      - remo-net
    ports:
      - '5341:80'
      - '5342:80'
      - '5343:80'
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
